version: '3'
services: 
  database: 
    image: 'mongo'
    environment: 
      - MONGO_INITDB_DATABASE=graphql_db
      - MONGO_INITDB_ROOT_USERNAME=graphqldb
      - MONGO_INITDB_ROOT_PASSWORD=secret_graphqldb
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'